
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 17 18:39:09 CST 2013
//----------------------------------------------------

package syntactic;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int SHR_ASSIGN = 42;
  public static final int SHR = 55;
  public static final int DIVIDE = 30;
  public static final int XOR_ASSIGN = 44;
  public static final int SHL = 54;
  public static final int CHAR = 4;
  public static final int GE = 53;
  public static final int LPAREN = 16;
  public static final int CONTINUE = 12;
  public static final int INT = 5;
  public static final int FOR = 11;
  public static final int MINUS = 28;
  public static final int RPAREN = 17;
  public static final int AND = 47;
  public static final int SUB_ASSIGN = 40;
  public static final int NOT = 26;
  public static final int SEMICOLON = 20;
  public static final int SIZEOF = 15;
  public static final int LT = 50;
  public static final int OR = 46;
  public static final int ELLIPSIS = 59;
  public static final int COMMA = 24;
  public static final int INC = 56;
  public static final int OPXOR = 33;
  public static final int NUM = 62;
  public static final int TYPEDEF = 2;
  public static final int PLUS = 27;
  public static final int ASSIGN = 35;
  public static final int IF = 8;
  public static final int ID = 63;
  public static final int PTR = 58;
  public static final int DOT = 23;
  public static final int LE = 51;
  public static final int ADD_ASSIGN = 39;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int OPAND = 34;
  public static final int OPOR = 32;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 41;
  public static final int MOD = 31;
  public static final int Char = 60;
  public static final int BREAK = 13;
  public static final int VOID = 3;
  public static final int EQ = 48;
  public static final int MOD_ASSIGN = 38;
  public static final int DIV_ASSIGN = 37;
  public static final int TIMES = 29;
  public static final int LSQBRA = 21;
  public static final int UNION = 7;
  public static final int LBRACE = 18;
  public static final int ELSE = 9;
  public static final int AND_ASSIGN = 43;
  public static final int String = 61;
  public static final int WHILE = 10;
  public static final int OR_ASSIGN = 45;
  public static final int RSQBRA = 22;
  public static final int RBRACE = 19;
  public static final int NE = 49;
  public static final int MUL_ASSIGN = 36;
  public static final int NEGATE = 25;
  public static final int DEC = 57;
  public static final int STRUCT = 6;
  public static final int GT = 52;
}

