/* The following code was generated by JFlex 1.4.3 on 4/17/13 6:39 PM */

package syntactic;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/17/13 6:39 PM from the specification file
 * <tt>appetizer.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYCOMMENT = 6;
  public static final int YYCOMMENT_TWO = 8;
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int PRE = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\1\1\0\1\13\1\2\22\0\1\13\1\57\1\70"+
    "\1\71\1\4\1\62\1\64\1\14\1\45\1\46\1\21\1\60\1\54"+
    "\1\61\1\53\1\20\1\5\7\7\2\6\1\0\1\55\1\66\1\65"+
    "\1\67\2\0\6\12\21\3\1\11\2\3\1\51\1\15\1\52\1\63"+
    "\1\4\1\0\1\34\1\42\1\32\1\25\1\24\1\26\1\3\1\33"+
    "\1\31\1\3\1\43\1\40\1\3\1\16\1\30\1\23\1\3\1\35"+
    "\1\36\1\17\1\37\1\27\1\41\1\11\1\22\1\44\1\47\1\10"+
    "\1\50\1\56\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\2\4\1\5\1\1\1\3"+
    "\1\6\1\7\12\3\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\40\1\42\1\0"+
    "\1\43\1\44\2\0\1\3\1\45\1\46\1\47\1\50"+
    "\1\51\4\3\1\52\10\3\1\0\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\74\1\75"+
    "\1\76\2\77\2\3\1\100\1\3\1\101\10\3\1\102"+
    "\1\103\1\104\1\3\1\105\1\106\1\3\1\107\13\3"+
    "\1\110\1\111\1\112\2\3\1\113\1\114\1\115\1\116"+
    "\1\3\1\117";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\350\0\u0122\0\u015c"+
    "\0\u0196\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c"+
    "\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc"+
    "\0\u0536\0\350\0\350\0\350\0\350\0\350\0\350\0\u0570"+
    "\0\350\0\350\0\350\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692"+
    "\0\u06cc\0\u0706\0\u0740\0\u077a\0\350\0\350\0\u07b4\0\u07ee"+
    "\0\350\0\350\0\350\0\u0828\0\u0862\0\u089c\0\350\0\350"+
    "\0\u08d6\0\u0910\0\u094a\0\350\0\350\0\350\0\350\0\350"+
    "\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u015c\0\u0a6c\0\u0aa6\0\u0ae0"+
    "\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c\0\350\0\350"+
    "\0\350\0\350\0\350\0\350\0\350\0\350\0\350\0\350"+
    "\0\350\0\350\0\u0c76\0\350\0\u0cb0\0\350\0\350\0\350"+
    "\0\350\0\u089c\0\350\0\u08d6\0\u0cea\0\u0d24\0\u015c\0\u0d5e"+
    "\0\u015c\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0ef4"+
    "\0\u0f2e\0\350\0\350\0\350\0\u0f68\0\u015c\0\u015c\0\u0fa2"+
    "\0\u015c\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe\0\u1138"+
    "\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u015c\0\u015c\0\u015c\0\u125a"+
    "\0\u1294\0\u015c\0\u015c\0\u015c\0\u015c\0\u12ce\0\u015c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\5\1\11\2\12\1\13"+
    "\2\10\1\6\1\14\1\5\1\10\1\15\1\16\1\17"+
    "\2\10\1\20\1\10\1\21\1\22\1\10\1\23\1\24"+
    "\2\10\1\25\1\26\1\27\1\10\1\30\1\31\2\10"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\2\0\12\57"+
    "\1\60\52\57\1\61\1\57\1\62\1\63\111\62\1\64"+
    "\50\62\73\0\1\6\73\0\5\10\1\0\2\10\3\0"+
    "\2\10\2\0\23\10\32\0\1\65\1\0\1\65\2\66"+
    "\65\0\3\12\72\0\1\67\54\0\1\70\4\0\15\71"+
    "\1\72\54\71\3\0\5\10\1\0\2\10\3\0\2\10"+
    "\2\0\1\73\22\10\45\0\1\74\1\75\43\0\1\76"+
    "\24\0\1\77\44\0\1\100\7\0\5\10\1\0\2\10"+
    "\3\0\2\10\2\0\16\10\1\101\4\10\30\0\5\10"+
    "\1\0\2\10\3\0\2\10\2\0\6\10\1\102\14\10"+
    "\30\0\5\10\1\0\2\10\3\0\2\10\2\0\6\10"+
    "\1\103\14\10\30\0\5\10\1\0\2\10\3\0\1\104"+
    "\1\10\2\0\4\10\1\105\16\10\30\0\5\10\1\0"+
    "\2\10\3\0\2\10\2\0\6\10\1\106\2\10\1\107"+
    "\11\10\30\0\5\10\1\0\2\10\3\0\2\10\2\0"+
    "\2\10\1\110\20\10\30\0\5\10\1\0\2\10\3\0"+
    "\1\10\1\111\2\0\7\10\1\112\13\10\30\0\5\10"+
    "\1\0\2\10\3\0\1\113\1\10\2\0\23\10\30\0"+
    "\5\10\1\0\2\10\3\0\2\10\2\0\11\10\1\114"+
    "\11\10\30\0\5\10\1\0\2\10\3\0\2\10\2\0"+
    "\13\10\1\115\7\10\100\0\1\116\103\0\1\117\64\0"+
    "\1\120\4\0\1\121\65\0\1\122\3\0\1\123\1\0"+
    "\1\124\67\0\1\125\71\0\1\126\70\0\1\127\1\130"+
    "\71\0\1\131\71\0\1\132\1\133\70\0\1\134\1\0"+
    "\1\135\2\0\1\57\2\0\12\57\1\0\52\57\1\0"+
    "\1\57\16\0\1\136\1\137\15\0\1\140\32\0\1\141"+
    "\21\0\1\63\56\0\1\65\1\0\1\65\67\0\4\142"+
    "\1\0\1\142\11\0\3\142\3\0\1\142\1\0\1\142"+
    "\5\0\1\142\43\0\1\143\55\0\1\71\1\0\12\71"+
    "\1\144\55\71\3\0\5\10\1\0\2\10\3\0\2\10"+
    "\2\0\1\10\1\145\21\10\30\0\5\10\1\0\2\10"+
    "\3\0\2\10\2\0\14\10\1\146\6\10\30\0\5\10"+
    "\1\0\2\10\3\0\2\10\2\0\13\10\1\147\7\10"+
    "\30\0\5\10\1\0\2\10\3\0\2\10\2\0\7\10"+
    "\1\150\13\10\30\0\5\10\1\0\2\10\3\0\1\10"+
    "\1\151\2\0\23\10\30\0\5\10\1\0\2\10\3\0"+
    "\1\152\1\10\2\0\23\10\30\0\5\10\1\0\2\10"+
    "\3\0\2\10\2\0\12\10\1\153\10\10\30\0\5\10"+
    "\1\0\2\10\3\0\1\10\1\154\2\0\23\10\30\0"+
    "\5\10\1\0\2\10\3\0\2\10\2\0\13\10\1\155"+
    "\7\10\30\0\5\10\1\0\2\10\3\0\2\10\2\0"+
    "\22\10\1\156\30\0\5\10\1\0\2\10\3\0\2\10"+
    "\2\0\7\10\1\157\13\10\30\0\5\10\1\0\2\10"+
    "\3\0\2\10\2\0\7\10\1\160\13\10\30\0\5\10"+
    "\1\0\2\10\3\0\2\10\2\0\2\10\1\161\20\10"+
    "\100\0\1\162\103\0\1\163\71\0\1\164\7\0\5\10"+
    "\1\0\2\10\3\0\2\10\2\0\2\10\1\165\20\10"+
    "\30\0\5\10\1\0\2\10\3\0\2\10\2\0\2\10"+
    "\1\166\20\10\30\0\5\10\1\0\2\10\3\0\2\10"+
    "\2\0\3\10\1\167\17\10\30\0\5\10\1\0\2\10"+
    "\3\0\1\10\1\170\2\0\23\10\30\0\5\10\1\0"+
    "\2\10\3\0\2\10\2\0\13\10\1\171\7\10\30\0"+
    "\5\10\1\0\2\10\3\0\2\10\2\0\15\10\1\172"+
    "\5\10\30\0\5\10\1\0\2\10\3\0\2\10\2\0"+
    "\15\10\1\173\5\10\30\0\5\10\1\0\2\10\3\0"+
    "\2\10\2\0\2\10\1\174\20\10\30\0\5\10\1\0"+
    "\2\10\3\0\2\10\2\0\6\10\1\175\14\10\30\0"+
    "\5\10\1\0\2\10\3\0\2\10\2\0\16\10\1\176"+
    "\4\10\30\0\5\10\1\0\2\10\3\0\2\10\2\0"+
    "\12\10\1\177\10\10\30\0\5\10\1\0\2\10\3\0"+
    "\2\10\2\0\3\10\1\200\17\10\30\0\5\10\1\0"+
    "\2\10\3\0\2\10\2\0\7\10\1\201\13\10\30\0"+
    "\5\10\1\0\2\10\3\0\2\10\2\0\13\10\1\202"+
    "\7\10\30\0\5\10\1\0\2\10\3\0\2\10\2\0"+
    "\10\10\1\203\12\10\30\0\5\10\1\0\2\10\3\0"+
    "\2\10\2\0\6\10\1\204\14\10\30\0\5\10\1\0"+
    "\2\10\3\0\1\205\1\10\2\0\23\10\30\0\5\10"+
    "\1\0\2\10\3\0\2\10\2\0\2\10\1\206\20\10"+
    "\30\0\5\10\1\0\2\10\3\0\2\10\2\0\21\10"+
    "\1\207\1\10\30\0\5\10\1\0\2\10\3\0\2\10"+
    "\2\0\2\10\1\210\20\10\30\0\5\10\1\0\2\10"+
    "\3\0\1\211\1\10\2\0\23\10\30\0\5\10\1\0"+
    "\2\10\3\0\1\212\1\10\2\0\23\10\30\0\5\10"+
    "\1\0\2\10\3\0\1\10\1\213\2\0\23\10\30\0"+
    "\5\10\1\0\2\10\3\0\2\10\2\0\4\10\1\214"+
    "\16\10\30\0\5\10\1\0\2\10\3\0\2\10\2\0"+
    "\4\10\1\215\16\10\30\0\5\10\1\0\2\10\3\0"+
    "\2\10\2\0\15\10\1\216\5\10\30\0\5\10\1\0"+
    "\2\10\3\0\2\10\2\0\2\10\1\217\20\10\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4872];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\23\1\6\11\1\1\3\11\11\1\2\11"+
    "\2\1\3\11\2\1\1\0\2\11\2\0\1\1\5\11"+
    "\15\1\1\0\14\11\1\1\1\11\1\1\4\11\1\1"+
    "\1\11\16\1\3\11\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	String string = new String();

	private void err(String message) {
		System.out.println("Scanning error in line " + yyline + ", column " + yycolumn + ": " + message);
	}

	private java_cup.runtime.Symbol tok(int kind) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn);
	}

	private java_cup.runtime.Symbol tok(int kind, Object value) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn, value);
	}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 66: 
          { System.out.print("..."); return tok(ELLIPSIS);
          }
        case 80: break;
        case 5: 
          { System.out.print("|"); return tok(OPOR);
          }
        case 81: break;
        case 23: 
          { System.out.print("&"); return tok(OPAND);
          }
        case 82: break;
        case 8: 
          { System.out.print("("); return tok(LPAREN);
          }
        case 83: break;
        case 3: 
          { System.out.print("<ID, "+ yytext() +">"); return tok(ID, yytext());
          }
        case 84: break;
        case 70: 
          { System.out.print("void"); return tok(VOID);
          }
        case 85: break;
        case 59: 
          { string += "\\t";
          }
        case 86: break;
        case 4: 
          { System.out.print("<DecInteger, "+ yytext() +">"); return tok(NUM, new Integer(yytext()));
          }
        case 87: break;
        case 47: 
          { System.out.print("-="); return tok(SUB_ASSIGN);
          }
        case 88: break;
        case 79: 
          { System.out.print("continue"); return tok(CONTINUE);
          }
        case 89: break;
        case 21: 
          { System.out.print("%"); return tok(MOD);
          }
        case 90: break;
        case 41: 
          { System.out.print("*="); return tok(MUL_ASSIGN);
          }
        case 91: break;
        case 60: 
          { string += "\\r";
          }
        case 92: break;
        case 64: 
          { System.out.print("for"); return tok(FOR);
          }
        case 93: break;
        case 75: 
          { System.out.print("return"); return tok(RETURN);
          }
        case 94: break;
        case 46: 
          { System.out.print("--"); return tok(DEC);
          }
        case 95: break;
        case 49: 
          { System.out.print("%="); return tok(MOD_ASSIGN);
          }
        case 96: break;
        case 36: 
          { System.out.print("|="); return tok(OR_ASSIGN);
          }
        case 97: break;
        case 65: 
          { System.out.print("int"); return tok(INT);
          }
        case 98: break;
        case 26: 
          { System.out.print(">"); return tok(GT);
          }
        case 99: break;
        case 69: 
          { System.out.print("else"); return tok(ELSE);
          }
        case 100: break;
        case 34: 
          { System.out.print("<OctInteger, "+ yytext() +">");
		int x = 0;
		String st = yytext();
		for (int i = 1; i < st.length(); ++i)
			x = x * 8 + (st.charAt(i) - '0');
	 	return tok(NUM, new Integer(x));
          }
        case 101: break;
        case 58: 
          { string += "\\n";
          }
        case 102: break;
        case 22: 
          { System.out.print("^"); return tok(OPXOR);
          }
        case 103: break;
        case 52: 
          { System.out.print("&="); return tok(AND_ASSIGN);
          }
        case 104: break;
        case 43: 
          { System.out.print("!="); return tok(NE) ;
          }
        case 105: break;
        case 44: 
          { System.out.print("++"); return tok(INC);
          }
        case 106: break;
        case 37: 
          { yybegin(YYCOMMENT_TWO);
          }
        case 107: break;
        case 15: 
          { System.out.print(","); return tok(COMMA);
          }
        case 108: break;
        case 25: 
          { System.out.print("<"); return tok(LT);
          }
        case 109: break;
        case 67: 
          { System.out.print("<<="); return tok(SHL_ASSIGN);
          }
        case 110: break;
        case 73: 
          { System.out.print("while"); return tok(WHILE);
          }
        case 111: break;
        case 19: 
          { System.out.print("+"); return tok(PLUS);
          }
        case 112: break;
        case 31: 
          { yybegin(YYINITIAL);
  								   System.out.print("<String, "+ string +">");
                                   return tok(String, string);
          }
        case 113: break;
        case 50: 
          { System.out.print("^="); return tok(XOR_ASSIGN);
          }
        case 114: break;
        case 12: 
          { System.out.print("["); return tok(LSQBRA);
          }
        case 115: break;
        case 38: 
          { yybegin(YYCOMMENT);
          }
        case 116: break;
        case 20: 
          { System.out.print("-"); return tok(MINUS);
          }
        case 117: break;
        case 27: 
          { string = ""; yybegin(STRING);
          }
        case 118: break;
        case 63: 
          { System.out.print("<Char, "+ yytext() +">"); return tok(Char, yytext());
          }
        case 119: break;
        case 9: 
          { System.out.print(")"); return tok(RPAREN);
          }
        case 120: break;
        case 78: 
          { System.out.print("typedef"); return tok(TYPEDEF);
          }
        case 121: break;
        case 16: 
          { System.out.print(";"); return tok(SEMICOLON);
          }
        case 122: break;
        case 2: 
          { System.out.print(yytext());
          }
        case 123: break;
        case 24: 
          { System.out.print("="); return tok(ASSIGN);
          }
        case 124: break;
        case 68: 
          { System.out.print(">>="); return tok(SHR_ASSIGN);
          }
        case 125: break;
        case 54: 
          { System.out.print("<="); return tok(LE);
          }
        case 126: break;
        case 13: 
          { System.out.print("]"); return tok(RSQBRA);
          }
        case 127: break;
        case 1: 
          { throw new RuntimeException("Illegal character " + yytext() + " in line " + (yyline + 1) + ", column " + (yycolumn + 1));
          }
        case 128: break;
        case 6: 
          { System.out.print("/"); return tok(DIVIDE);
          }
        case 129: break;
        case 29: 
          { string += yytext();
          }
        case 130: break;
        case 45: 
          { System.out.print("+="); return tok(ADD_ASSIGN);
          }
        case 131: break;
        case 71: 
          { System.out.print("char"); return tok(CHAR);
          }
        case 132: break;
        case 18: 
          { System.out.print("!"); return tok(NOT);
          }
        case 133: break;
        case 40: 
          { err("Comment symbol do not match!");
          }
        case 134: break;
        case 10: 
          { System.out.print("{"); return tok(LBRACE);
          }
        case 135: break;
        case 33: 
          { yybegin(YYINITIAL);
          }
        case 136: break;
        case 7: 
          { System.out.print("*"); return tok(TIMES);
          }
        case 137: break;
        case 53: 
          { System.out.print("=="); return tok(EQ);
          }
        case 138: break;
        case 14: 
          { System.out.print("."); return tok(DOT);
          }
        case 139: break;
        case 30: 
          { string += "\\";
          }
        case 140: break;
        case 72: 
          { System.out.print("union"); return tok(UNION);
          }
        case 141: break;
        case 48: 
          { System.out.print("->"); return tok(PTR);
          }
        case 142: break;
        case 42: 
          { System.out.print("if"); return tok(IF);
          }
        case 143: break;
        case 77: 
          { System.out.print("sizeof"); return tok(SIZEOF);
          }
        case 144: break;
        case 62: 
          { System.out.print("<HexInteger, "+ yytext() +">");
		int x = 0;
		String st = yytext();
		for (int i = 2; i < st.length(); ++i) {
			int t = 0;
			if ('0' <= st.charAt(i) && st.charAt(i) <= '9')
				t = st.charAt(i) - '0';
			else
				if ('A' <= st.charAt(i) && st.charAt(i) <= 'F')
					t = st.charAt(i) - 'A' + 10;
				else
					t = st.charAt(i) - 'a' + 10;
			x = x * 16 + t;
			}
	 	return tok(NUM, new Integer(x));
          }
        case 145: break;
        case 51: 
          { System.out.print("&&"); return tok(AND);
          }
        case 146: break;
        case 61: 
          { string += "\\\"";
          }
        case 147: break;
        case 11: 
          { System.out.print("}"); return tok(RBRACE);
          }
        case 148: break;
        case 17: 
          { System.out.print("~"); return tok(NEGATE);
          }
        case 149: break;
        case 28: 
          { yybegin(PRE);
          }
        case 150: break;
        case 39: 
          { System.out.print("/="); return tok(DIV_ASSIGN);
          }
        case 151: break;
        case 35: 
          { System.out.print("||"); return tok(OR);
          }
        case 152: break;
        case 74: 
          { System.out.print("break"); return tok(BREAK);
          }
        case 153: break;
        case 56: 
          { System.out.print(">="); return tok(GE);
          }
        case 154: break;
        case 76: 
          { System.out.print("struct"); return tok(STRUCT);
          }
        case 155: break;
        case 55: 
          { System.out.print("<<"); return tok(SHL);
          }
        case 156: break;
        case 57: 
          { System.out.print(">>"); return tok(SHR);
          }
        case 157: break;
        case 32: 
          { 
          }
        case 158: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	{
		if (yystate() == YYCOMMENT) {
			err("Comment symbol do not match (EOF)!");
		}
		return tok(EOF, null);
	}
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
